CREATE TABLE `user2` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `user_mobile` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `user_passwd` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `user_status` INT(2) DEFAULT NULL,
  `email` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=151 DEFAULT CHARSET=utf8 COLLATE=utf8_bin
